### ISSUE TITLE
Unable to monitor energy for package and core domains

### ISSUE THREAD

**Issue by nikhil153** [powerapi-ng/pyJoules#14]
Hi, 

I am trying to compare energy footprint of two different Intel processors. I am able to collect energy data for all the domains ("package_0; dram_0; core_0; uncore_0") on "Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz". However, I only see data for "dram_0;dram_1" domains for the "Intel(R) Xeon(R) CPU E5-2683 v4 @ 2.10GHz".    

I am using a decorator to monitor energy. 

Any suggestions?

Thanks!

**Comment by nikhil153** [comment]
I figured out the issue. This happens on the multi-socket machines with mismatch between RAPL package indexing on the machine and socket index numbering in rapl_device.py.

**Comment by johannabar** [comment]
Hello! I am facing the same issue, I am only getting dram and none of the other metrics for the CPU, 

I was wondering how you managed to make it work in the end? By changing the rapl_device.py file? Thanks!

**Comment by venugopalansgr** [comment]
I faced the same issue and taking note of what nikhil153 mentioned, did the following fix in line 136 of rapl_device.py:

 if domain_name_file.readline() == 'package-' + str(socket_id) + '\n': #removed this
 if "package-" in domain_name_file.readline(): #replaced with this
 
 Hope this helps others too!
